# Generated by Django 4.2.5 on 2023-09-27 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='share_with',
            field=models.ManyToManyField(related_name='shared_tweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
