# Generated by Django 4.2.5 on 2023-10-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.IntegerField(blank=True, max_length=11),
        ),
    ]
